package com.example.cashback.models.Flipkart

import com.google.gson.annotations.SerializedName

data class FlipkartCategoryApiListingsResponse(

    @SerializedName("food_nutrition") val food_nutrition : FlipkartCategoryFood_nutritionResponse,
    @SerializedName("televisions") val televisions : FlipkartCategoryTelevisionResponse,
    @SerializedName("landline_phones") val landline_phones : FlipkartCategoryLandline_phonesResponse,
    @SerializedName("tv_video_accessories") val tv_video_accessories : FlipkartCategoryTv_video_accessoriesResponse,
    @SerializedName("software") val software : FlipkartCategorySoftwareResponse,
    @SerializedName("computer_storage") val computer_storage : FlipkartCategoryComputer_storageResponse,
    @SerializedName("fragrances") val fragrances : FlipkartCategoryFragnanceResponse,
    @SerializedName("network_components") val network_components : FlipkartCategoryNetwork_componentsResponse,
    @SerializedName("e_learning") val e_learning : FlipkartCategoryElerningResponse,
    @SerializedName("video_players") val video_players : FlipkartCategoryVideoplayersResponse,
    @SerializedName("mens_clothing") val mens_clothing : FlipkartCategoryMens_clothingResponse,
    @SerializedName("music_movies_posters") val music_movies_posters : FlipkartCategoryMusic_movie_posterResponse,
    @SerializedName("furniture") val furniture : FlipkartCategoryFurnitureResponse,
    @SerializedName("bags_wallets_belts") val bags_wallets_belts : FlipkartCategoryBags_wallets_beltsResponse,
    @SerializedName("mobiles") val mobiles : FlipkartCategoryMobilesResponse,
    @SerializedName("kids_clothing") val kids_clothing : FlipkartCategoryKids_clothingResponse,
    @SerializedName("kids_footwear") val kids_footwear : FlipkartCategoryKids_footwearResponse,
    @SerializedName("pet_supplies") val pet_supplies : FlipkartCategoryPetsuppliesResponse,
    @SerializedName("mens_footwear") val mens_footwear : FlipkartCategorymens_footwearResponse,
    @SerializedName("air_coolers") val air_coolers : FlipkartCategoryAir_coolersResponse,
    @SerializedName("home_entertainment") val home_entertainment : FlipkartCategoryHome_entertaimentResponse,
    @SerializedName("watches") val watches : FlipkartCategoryWatchesResponse,
    @SerializedName("sunglasses") val sunglasses : FlipkartCategorySunglassesResponse,
    @SerializedName("eyewear") val eyewear : FlipkartCategoryeyewearResponse,
    @SerializedName("computer_components") val computer_components : FlipkartCategoryComputer_componentsResponse,
    @SerializedName("laptop_accessories") val laptop_accessories : FlipkartCategoryLaptopAccessoriesResponse,
    @SerializedName("womens_clothing") val womens_clothing : FlipkartCategoryWomenClothingResponse,
    @SerializedName("mobile_accessories") val mobile_accessories : FlipkartCategoryMobile_accesoriesResponse,
    @SerializedName("camera_accessories") val camera_accessories : FlipkartCategoryCamera_accessoriesResponse,
    @SerializedName("air_conditioners") val air_conditioners : FlipkartCategoryAir_conditionersResponse,
    @SerializedName("luggage_travel") val luggage_travel : FlipkartCategoryLuggagetavelResponse,
    @SerializedName("automotive") val automotive : FlipkartCategoryAutomotiveResponse,
    @SerializedName("tablets") val tablets : FlipkartCategoryTabletsResponse,
    @SerializedName("refrigerator") val refrigerator : FlipkartCategoryRefrigeratorResponse,
    @SerializedName("home_improvement_tools") val home_improvement_tools : FlipkartCategoryHome_improvement_toolsResponse,
    @SerializedName("computer_peripherals") val computer_peripherals : FlipkartCategoryComputer_peripheralsResponse,
    @SerializedName("stationery_office_supplies") val stationery_office_supplies : FlipkartCategoryStationary_suppliesResponse,
    @SerializedName("sports_fitness") val sports_fitness : FlipkartCategorySports_fitnessResponse,
    @SerializedName("baby_care") val baby_care : FlipkartCategoryBaby_careResponse,
    @SerializedName("cameras") val cameras : FlipkartCategoryCamerasResponse,
    @SerializedName("wearable_smart_devices") val wearable_smart_devices : FlipkartCategoryWearable_smart_devicesResponse,
    @SerializedName("audio_players") val audio_players : FlipkartCategoryAudio_playersResponse,
    @SerializedName("grooming_beauty_wellness") val grooming_beauty_wellness : FlipkartCategoryGrooming_beauty_wellnessResponse,
    @SerializedName("tablet_accessories") val tablet_accessories : FlipkartCategoryTablet_accessoriesResponse,
    @SerializedName("kitchen_appliances") val kitchen_appliances : FlipkartCategoryKitchen_applianceResponse,
    @SerializedName("microwave_ovens") val microwave_ovens : FlipkartCategoryMicrowave_ovensResponse,
    @SerializedName("laptops") val laptops : FlipkartCategoryLaptopsResponse,
    @SerializedName("washing_machine") val washing_machine : FlipkartCategoryWashing_machineResponse,
    @SerializedName("gaming") val gaming : FlipkartCategoryGamingResponse,
    @SerializedName("toys") val toys : FlipkartCategoryToysResponse,
    @SerializedName("home_appliances") val home_appliances : FlipkartCategoryHome_applianceResponse,
    @SerializedName("home_decor_and_festive_needs") val home_decor_and_festive_needs : FlipkartCategoryHome_decoretive_needsResponse,
    @SerializedName("home_and_kitchen_needs") val home_and_kitchen_needs : FlipkartCategoryHome_and_kitchen_needsResponse,
    @SerializedName("jewellery") val jewellery : FlipkartCategoryJewelleryResponse,
    @SerializedName("home_furnishing") val home_furnishing : FlipkartCategoryHome_furnishingResponse,
    @SerializedName("desktops") val desktops : FlipkartCategoryDesktopResponse,
    @SerializedName("womens_footwear") val womens_footwear : FlipkartCategoryWomen_FootwearResponse,
    @SerializedName("household_supplies") val household_supplies : FlipkartCategoryHousehold_suppliesResponse
)
